gcp:
  storage:
    bucket-name: ${GCS_BUCKET_NAME:hotel-room-images}
    project-id: ${GCP_PROJECT_ID:staycloud}

spring:
  application:
    name: room-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://10.10.0.11:8888}"
  cloud:
    config:
      fail-fast: false
      override-system-properties: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:hotelmongo@10.10.0.2:27017/hotel_rooms?authSource=admin}
  mongodb:
    uri: ${MONGODB_URI:mongodb://root:hotelmongo@10.10.0.2:27017/hotel_rooms?authSource=admin}
